---
title: "Simulation"
author: "Frank Edwards"
institute: School of Criminal Justice, Rutgers - Newark
output: binb::metropolis
---

```{r message = FALSE, warning = FALSE, echo=FALSE}
library(tidyverse)
### configure for variable text size with chunk option
def.chunk.hook  <- knitr::knit_hooks$get("chunk")
knitr::knit_hooks$set(chunk = function(x, options) {
  x <- def.chunk.hook(x, options)
  ifelse(options$size != "normalsize", paste0("\\", options$size,"\n\n", x, "\n\n \\normalsize"), x)
})
knitr::opts_chunk$set(warning=FALSE, message=FALSE, tidy = TRUE, size = "small")
```

# The Generalized Linear Model

## The linear model

We know we can model data as:

<!-- THIS IS THE LINEAR REGRESSION FORMULA -->
<!-- where epsilon is the error term -->

$$y = \beta_0 + \beta_1x_1 \cdots \beta_nx_n + \varepsilon$$ \pause

Or, more succinctly:

$$ y =  \mathbf{X} \mathbf{\beta} + \varepsilon $$ \pause

Where the likelihood for the outcome conditional on the data takes the form:

$$ Y|X \sim Normal(\mu, \sigma^2) $$ 

## Generalzing the linear model

The linear model: 

$$ Y|X \sim Normal(\mu, \sigma^2) $$

Can be written as a more general formulation for a likelihood function $f$

$$ Y|X \sim f(\mu, \sigma^2) $$ \pause

Now we can extend the (very) useful linear model to data with discrete outcomes

## Generalizing the linear model

An expected value $E(Y|X) = \mu$

A linear predictor: 

$$ \mathbf{X} \mathbf{\beta} $$ \pause

A link function $g$

$$ g(\mu) =  \mathbf{X} \mathbf{\beta} $$ \pause

$$ \mu =  g^{-1}(\mathbf{X} \mathbf{\beta}) $$

## From OLS to GLM

OLS:

$$ Y|X \sim Normal(\mu, \sigma^2) $$ 

GLM, for a likelihood function $f$ with parameters $\theta$: 

$$ Y|X \sim f(\theta) $$

## Models we'll consider this semester

- Binary data: logistic models \pause
- Categorical data: Multinomial models \pause
- Count data: Poisson and negative binomial models 

# Returning to the linear model

## What do we know about the linear regression model?

$$ y =  \mathbf{X} \mathbf{\beta} + \varepsilon $$
$$\varepsilon \sim Normal(0, \sigma^2)$$

OR

$$\mu =  \mathbf{X} \mathbf{\beta}$$
$$y \sim Normal(\mu, \sigma^2)$$


