---
title: "Interpreting logistic models"
author: "Frank Edwards"
date: "3/10/2021"
output: binb::metropolis
---

```{r setup, echo = FALSE, message = FALSE}
library(tidyverse)
library(rstan)
library(rstanarm)
library(broom)
### to optimize stan model fitting for your computer, enable parallel processing
rstan_options(auto_write = TRUE)
options(mc.cores = parallel::detectCores())



theme_set(theme_bw())
def.chunk.hook  <- knitr::knit_hooks$get("chunk")
knitr::knit_hooks$set(chunk = function(x, options) {
  x <- def.chunk.hook(x, options)
  ifelse(options$size != "normalsize", paste0("\\", options$size,"\n\n", x, "\n\n \\normalsize"), x)
})
knitr::opts_chunk$set(warning=FALSE, message=FALSE, tidy = TRUE, size = "small")
```

## Prediction and logistic regression

1. Subset the data into training and test data
2. Estimate the model on the training data
3. Predict on the test data
4. Evaluate accuracy

```{r echo = F}
dat<-read_csv("./data/titanic.csv")
### set up test and training data with a simple random sample
training1<-dat %>% 
  sample_frac(0.75)
test1<-dat %>% 
  anti_join(training1)
write_csv(training1, "./data/titanic_training1.csv")
write_csv(test1, "./data/titanic_test1.csv")

training2<-dat %>% 
  filter(Age>18)
test2<-dat %>% 
  anti_join(training2)
write_csv(training2, "./data/titanic_training2.csv")
write_csv(test2, "./data/titanic_test2d.csv")

```

