---
title: "HW5"
author: "Frank Edwards"
date: "3/1/2019"
output: html_document
---

For this homework, use titanic.csv in ./HW/data/titanic.csv

The data contains the following variables:

- Survived: a binary indicating survival
- Pclass: a categorical indicating passenger class (first being the most expensive)
- Name: the passenger's name
- Sex: the passenger's sex (character)
- Age: the passenger's age
- Siblings/Spouses Aboard: an integer with how many sibs/spouses a passenger had aboard
- Parents/Children Aboard: an integer with how many parents or children a passenger had aboard
- Fare: The cost of the passenger's ticket

For this homework, you will provide an analysis of why some passengers died on the Titanic while others survived. Provide an appropriate description and exploration of the data, an explanation of your theoretical approach, and summaries and visualizations of any statistical models estimated.

Defend your modeling choices through a both a) theoretical motivations and b) an empirical inspection of model fit. Based on your empirical inspection of your model, you may choose to revise your initial modeling decisions. I encourage this iterative process. Please provide details for all models you estimate along the way.

I expect this to take the form of a mini-paper. Pretend that you are writing for an audience that is not your instructor. Provide me with adequate written detail to follow your reasoning, and enough visual and tabular information to support your claims. Conclude with a theoretically motivated and empirically informed statement about who was likely to die and survive on the Titanic. 