---
title: "HW6 - Cleaning data"
author: "Frank Edwards"
date: "3/8/2019"
output: html_document
---

For this homework, you will clean the Fatal Encounters dataset. A recent pull of the data is located in "./HW/data/fe_1_25_19.csv". Feel free to go to the FE website (fatalencounters.org) and download the latest if you want. Just make sure to export it as .csv.

## Question 1

1. After reading in the data, give the resulting data frame columns a set of easy-to-use names
2. Create a new data frame that contains the age, sex, race/ethnicity, state, date, and cause of death

## Question 2

1. Using the variable originally named `Date of injury resulting in death (month/day/year)` in the FE data, create a new variable for the year of the death. Don't cheat and use the already existing year variable in the data. 
2. Convert the age variable to a numeric variable that is equal to the number of years a person was when they died. You will have to first clean messy values.
3. Convert the sex variable into a three category variable with values F, M, T
4. Recode the race/ethnicity variable into more compact labels: black, white, latinx, a_pi, am_ind, m_e. Recode race unspecified to be equal to NA, not a character. Remeber that NA has special meaning in R.
5. Recode cause of death into 4 categories of your choosing

## Question 3

1. Provide a visual that shows the distribution of your recoded cause of death variable
2. Provide a visual that shows the distribution of victim age in the data
3. Provide a visual that shows the count of all deaths over time

## Question 4

1. Add a new variable to your cleaned data using the variable "Official disposition of death...". This variable should be called "suicide" and will record whether the death was reported by police to be a suicide. 

2. Estimate a logistic regression that evaluates the probability that a victim was declared to have committed suicide. You may choose any variables in the cleaned data from Questions 1 or 2, or any other variables of your choosing. Briefly explain your choices and your model results. 