---
title: "Final paper rough draft"
author: "Frank Edwards"
date: "4/8/2019"
output: html_document
---

DUE by 5/22, 5PM

Provide as complete a draft of your final paper as you are able. Below, I provide a general outline for your paper. You don't have to follow this exact script, but you do need to include to each of the components in your paper. This is your best chance to get feedback on your progress prior to submitting your final paper. It's in your best interest to provide me with as complete a draft as you can, but of course I understand that the work won't be complete at this stage. 

I recommend authoring your document in RMarkdown. You need not provide a copy of the code you use in the paper. You can disable code and messages printing to your report with the flags on the code chunk header echo = FALSE, message = FALSE.

*General outline*

- Provide a brief introduction to your question / topic, along with your theoretical approach to the question. You do not need to provide a detailed literature review.
- Describe the data you are using: how was it collected, what is its scope, what is its strengths, what are its limitations
- Provide a thorough exploration of your outcome variable and all theoretically relevant predictors.
- Describe your statistical questions and modeling approach
- Present and interpret your model(s)
- Provide relevant tables or data visuals to aid in interpreting your model
- Briefly discuss the implications of your findings.